name: Deploy to GitHub Pages

on:
  # Déclenche le workflow à chaque fois qu'une modification est poussée sur la branche `main`
  push:
    branches: [main]
  # Permet d'exécuter ce workflow manuellement depuis l'onglet Actions de GitHub.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Vous pouvez définir une version spécifique de Node.js

      - name: Install dependencies
        run: npm install  # Si vous utilisez npm, ou ajustez pour yarn/pnpm si nécessaire

      - name: Build the project
        run: npm run build  # Assurez-vous que votre commande de build est correctement configurée

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # Branche cible pour le déploiement
          folder: public  # Dossier de sortie de votre build Astro (ajustez si nécessaire)
