name: Deploy to GitHub Pages

on:
  # Déclenche le workflow à chaque fois qu'une modification est poussée sur la branche `main`
  # Si vous utilisez une autre branche, remplacez `main` par le nom de votre branche.
  push:
    branches: [main]
  # Permet d'exécuter ce workflow manuellement depuis l'onglet Actions de GitHub.
  workflow_dispatch:

# Accorde les permissions nécessaires pour cloner le repo et effectuer le déploiement.
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install, build, and upload your site output
        uses: withastro/action@v2
        with:
          # path: . # Emplacement de votre projet Astro dans le repo, par défaut il est à la racine.
          # node-version: 20 # Version de Node à utiliser pour la construction du site, par défaut 20.
          # package-manager: pnpm@latest # Gestionnaire de paquets à utiliser. Vous pouvez préciser un autre comme npm, yarn, etc.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
